# Data Study

In [2]:
import pandas as pd

dataset = pd.read_csv('Train_call.txt', sep='\t')
labels = pd.read_csv('Train_clinical.txt', sep='\t')

In [3]:
dataset.shape

(2834, 104)

In [4]:
dataset.head(20)

Chromosome    Start      End  Nclone  Array.129  Array.34  Array.67  \
0            1     2927    43870       3          0         0         0   
1            1    85022   216735       4          0         0         0   
2            1   370546   372295       4          0         0         0   
3            1   471671   786483       5          0         0         0   
4            1   792533   907406      13          0         0         0   
5            1   912799  1266212      96          0         0         0   
6            1  1271190  1590570      45          0         0         0   
7            1  1676445  1703748       4          0         0         0   
8            1  1738295  2477597     104          0         0         0   
9            1  2481927  2562342      14          0         0         0   
10           1  2574555  2580342       2          0         0         0   
11           1  2611444  2641811      12          0         0         0   
12           1  2643540  2645074       2          0         0         0   
13           1  2664285  2665530       2          0         0         0   
14           1  2672694  2832087      14          0         0         0   
15           1  2854198  2856899       2          0         0         0   
16           1  2870100  2880675       6          0         0         0   
17           1  2882919  2901629       9          0         0         0   
18           1  2903052  3112977      27          0         0         0   
19           1  3125822  3135062       2          2         0         0   

    Array.24  Array.22  Array.36  ...  Array.64  Array.89  Array.30  Array.35  \
0          0         0         0  ...         0         0         1         0   
1          0         0         0  ...         0         0         1         0   
2          0         0         0  ...         0         0         1         0   
3          0         0         0  ...         0         1         1         0   
4          0         0         0  ...         0         1         1         0   
5          0         0         0  ...         0         0         1         0   
6          0         0         0  ...         0         0         1         0   
7         -1         0         0  ...         0         0         1         0   
8          0         0         0  ...         0         0         1         0   
9          0         0         0  ...         0         0         1         0   
10         0         0         0  ...         0         0         1         0   
11         0         1         0  ...         1         1         1         0   
12         0         1         0  ...         1         1         1         0   
13         0         0         0  ...         1         0         1         0   
14         0         0         0  ...         0         0         1         0   
15         0         0         0  ...         0         0         1         0   
16         0         1         0  ...         1         1         1         0   
17         0         1         0  ...         1         1         1         0   
18         0         0         0  ...         0         0         1         0   
19         0         0         0  ...         0         0         1         0   

    Array.93  Array.10  Array.123  Array.100  Array.134  Array.130  
0          0         0          0          0         -1          0  
1          0         0          0          0         -1          0  
2          1         0          0          0         -1          0  
3          1         0          0          0         -1          0  
4          1         0          0          0         -1          0  
5          1         0          0          0         -1          0  
6          1         0          0          0         -1          0  
7          1         0          0          0         -1          0  
8          0         0          0          0         -1          0  
9          0         0          0   

In [5]:
dataset_transposed = dataset.T
dataset_transposed = dataset_transposed.drop(['Start', 'End', 'Nclone', 'Chromosome'])
dataset_transposed = dataset_transposed.reset_index()

In [6]:
trainset = pd.concat([dataset_transposed, labels], axis=1)

In [7]:
trainset = trainset.set_index('Sample')
trainset = trainset.drop(columns = ['index'])

In [8]:
trainset

0  1  2  3  4  5  6  7  8  9  ...  2825  2826  2827  2828  2829  \
Sample                                   ...                                 
Array.129  0  0  0  0  0  0  0  0  0  0  ...     2     2     2     0     1   
Array.34   0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.67   0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.24   0  0  0  0  0  0  0 -1  0  0  ...     0     0     0     0     0   
Array.22   0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
...       .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   
Array.10   0  0  0  0  0  0  0  0  0  0  ...     1     0     1     1     1   
Array.123  0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.100  0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.134 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  ...     1     1     1     1     1   
Array.130  0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   

           2830  2831  2832  2833    Subgroup  
Sample                                         
Array.129     1     1     1     1       HER2+  
Array.34      1     1     1     1         HR+  
Array.67      1     1     1     1         HR+  
Array.24      0     0     0     0  Triple Neg  
Array.22      1     1     1     1  Triple Neg  
...         ...   ...   ...   ...         ...  
Array.10      1     1     1     1       HER2+  
Array.123     1     1     1     1         HR+  
Array.100     1     1     1     1         HR+  
Array.134     1     1     1     1         HR+  
Array.130     1     1     1     1       HER2+  

[100 rows x 2835 columns]

# Support Vector Classification

In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

In [10]:
# Separate the features and labels
#
X = trainset.iloc[:, :-1].values
y = trainset.iloc[:, -1].values

# Split the dataset into training and testing sets
#
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
# Scale the features
#
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
# Train the SVM model
#
classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [13]:
# Make predictions on the testing set
#
y_pred = classifier.predict(X_test)

# Evaluate the performance of the model
#
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)

Accuracy: 0.65
Confusion Matrix:
 [[4 1 0]
 [1 7 2]
 [1 2 2]]


# Naive Bayes Classification

In [14]:
from sklearn.naive_bayes import GaussianNB

In [15]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 70.00%


# Random Forest Classification

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [17]:
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 60.00%


# CV

In [1]:
from sklearn.model_selection import LeaveOneOut, KFold
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
dataset = pd.read_csv('Data/Train_call.txt', sep='\t')
labels = pd.read_csv('Data/Train_clinical.txt', sep='\t')

dataset_transposed = dataset.T
dataset_transposed = dataset_transposed.drop(['Start', 'End', 'Nclone', 'Chromosome'])
dataset_transposed = dataset_transposed.reset_index()

trainset = pd.concat([dataset_transposed, labels], axis=1)
trainset = trainset.set_index('Sample')
trainset = trainset.drop(columns = ['index'])

In [7]:
# Separate the features and labels
#
X = trainset.iloc[:, :-1].values
y = trainset.iloc[:, -1].values

# Split the dataset into training and testing sets
#
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
loo = LeaveOneOut()
loo_scores = []

In [13]:
for train_idx, test_idx in loo.split(X):
    # split the data into train and test sets for the outer loop
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    
    # define the inner loop
    inner_cv = KFold(n_splits=10)
    svc = SVC(C = 0.1, kernel='linear')
    inner_scores = []
    
    for inner_train_idx, inner_test_idx in inner_cv.split(X_train):
        # split the data into train and test sets for the inner loop
        X_inner_train, X_inner_test = X_train[inner_train_idx], X_train[inner_test_idx]
        y_inner_train, y_inner_test = y_train[inner_train_idx], y_train[inner_test_idx]
        
        # fit the model on the inner train set
        svc.fit(X_inner_train, y_inner_train)
        
        # evaluate the model on the inner test set
        inner_scores.append(svc.score(X_inner_test, y_inner_test))
    
    # calculate the mean inner score for this outer train-test split
    mean_inner_score = np.mean(inner_scores)
    
    # fit the model on the outer train set
    svc.fit(X_train, y_train)
    
    # evaluate the model on the outer test set
    loo_scores.append(svc.score(X_test, y_test))

In [14]:
# calculate the mean score over all outer train-test splits
mean_score = np.mean(loo_scores)
print(mean_score)

0.77
