# Data Study

In [2]:
import pandas as pd

dataset = pd.read_csv('Train_call.txt', sep='\t')
labels = pd.read_csv('Train_clinical.txt', sep='\t')

In [3]:
dataset.shape

(2834, 104)

In [5]:
dataset.head(20)

Chromosome    Start      End  Nclone  Array.129  Array.34  Array.67  \
0            1     2927    43870       3          0         0         0   
1            1    85022   216735       4          0         0         0   
2            1   370546   372295       4          0         0         0   
3            1   471671   786483       5          0         0         0   
4            1   792533   907406      13          0         0         0   
5            1   912799  1266212      96          0         0         0   
6            1  1271190  1590570      45          0         0         0   
7            1  1676445  1703748       4          0         0         0   
8            1  1738295  2477597     104          0         0         0   
9            1  2481927  2562342      14          0         0         0   
10           1  2574555  2580342       2          0         0         0   
11           1  2611444  2641811      12          0         0         0   
12           1  2643540  2645074       2          0         0         0   
13           1  2664285  2665530       2          0         0         0   
14           1  2672694  2832087      14          0         0         0   
15           1  2854198  2856899       2          0         0         0   
16           1  2870100  2880675       6          0         0         0   
17           1  2882919  2901629       9          0         0         0   
18           1  2903052  3112977      27          0         0         0   
19           1  3125822  3135062       2          2         0         0   

    Array.24  Array.22  Array.36  ...  Array.64  Array.89  Array.30  Array.35  \
0          0         0         0  ...         0         0         1         0   
1          0         0         0  ...         0         0         1         0   
2          0         0         0  ...         0         0         1         0   
3          0         0         0  ...         0         1         1         0   
4          0         0         0  ...         0         1         1         0   
5          0         0         0  ...         0         0         1         0   
6          0         0         0  ...         0         0         1         0   
7         -1         0         0  ...         0         0         1         0   
8          0         0         0  ...         0         0         1         0   
9          0         0         0  ...         0         0         1         0   
10         0         0         0  ...         0         0         1         0   
11         0         1         0  ...         1         1         1         0   
12         0         1         0  ...         1         1         1         0   
13         0         0         0  ...         1         0         1         0   
14         0         0         0  ...         0         0         1         0   
15         0         0         0  ...         0         0         1         0   
16         0         1         0  ...         1         1         1         0   
17         0         1         0  ...         1         1         1         0   
18         0         0         0  ...         0         0         1         0   
19         0         0         0  ...         0         0         1         0   

    Array.93  Array.10  Array.123  Array.100  Array.134  Array.130  
0          0         0          0          0         -1          0  
1          0         0          0          0         -1          0  
2          1         0          0          0         -1          0  
3          1         0          0          0         -1          0  
4          1         0          0          0         -1          0  
5          1         0          0          0         -1          0  
6          1         0          0          0         -1          0  
7          1         0          0          0         -1          0  
8          0         0          0          0         -1          0  
9          0         0          0   

In [63]:
dataset_transposed = dataset.T

In [64]:
dataset_transposed

0       1       2       3       4        5        6        7     \
Chromosome      1       1       1       1       1        1        1        1   
Start        2927   85022  370546  471671  792533   912799  1271190  1676445   
End         43870  216735  372295  786483  907406  1266212  1590570  1703748   
Nclone          3       4       4       5      13       96       45        4   
Array.129       0       0       0       0       0        0        0        0   
...           ...     ...     ...     ...     ...      ...      ...      ...   
Array.10        0       0       0       0       0        0        0        0   
Array.123       0       0       0       0       0        0        0        0   
Array.100       0       0       0       0       0        0        0        0   
Array.134      -1      -1      -1      -1      -1       -1       -1       -1   
Array.130       0       0       0       0       0        0        0        0   

               8        9     ...       2824       2825       2826       2827  \
Chromosome        1        1  ...         23         23         23         23   
Start       1738295  2481927  ...  151067607  152422390  152552851  152576854   
End         2477597  2562342  ...  152416606  152548587  152570071  152935130   
Nclone          104       14  ...        159         20          6         64   
Array.129         0        0  ...          2          2          2          2   
...             ...      ...  ...        ...        ...        ...        ...   
Array.10          0        0  ...          1          1          0          1   
Array.123         0        0  ...          1          1          1          1   
Array.100         0        0  ...          1          1          1          1   
Array.134        -1       -1  ...          1          1          1          1   
Array.130         0        0  ...          1          1          1          1   

                 2828       2829       2830       2831       2832       2833  
Chromosome         23         23         23         23         23         23  
Start       152994680  153062077  153466463  153504394  153938998  153997146  
End         153054487  153452633  153491568  153933426  153989329  154492924  
Nclone              5         57          4         55          5         43  
Array.129           0          1          1          1          1          1  
...               ...        ...        ...        ...        ...        ...  
Array.10            1          1          1          1          1          1  
Array.123           1          1          1          1          1          1  
Array.100           1          1          1          1          1          1  
Array.134           1          1          1          1          1          1  
Array.130           1          1          1          1          1          1  

[104 rows x 2834 columns]

In [65]:
dataset_transposed = dataset_transposed.drop(['Start', 'End', 'Nclone', 'Chromosome'])

In [78]:
dataset_transposed = dataset_transposed.reset_index()

In [67]:
labels

Sample    Subgroup
0   Array.129       HER2+
1    Array.34         HR+
2    Array.67         HR+
3    Array.24  Triple Neg
4    Array.22  Triple Neg
..        ...         ...
95   Array.10       HER2+
96  Array.123         HR+
97  Array.100         HR+
98  Array.134         HR+
99  Array.130       HER2+

[100 rows x 2 columns]

In [85]:
trainset = pd.concat([dataset_transposed, labels], axis=1)

In [86]:
trainset = trainset.drop(columns = ['Sample'])

In [114]:
trainset = trainset.rename(columns={"Samples" : "Sample"})

In [124]:
trainset = trainset.set_index('Sample')

In [127]:
trainset

0  1  2  3  4  5  6  7  8  9  ...  2825  2826  2827  2828  2829  \
Sample                                   ...                                 
Array.129  0  0  0  0  0  0  0  0  0  0  ...     2     2     2     0     1   
Array.34   0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.67   0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.24   0  0  0  0  0  0  0 -1  0  0  ...     0     0     0     0     0   
Array.22   0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
...       .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   
Array.10   0  0  0  0  0  0  0  0  0  0  ...     1     0     1     1     1   
Array.123  0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.100  0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   
Array.134 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  ...     1     1     1     1     1   
Array.130  0  0  0  0  0  0  0  0  0  0  ...     1     1     1     1     1   

           2830  2831  2832  2833    Subgroup  
Sample                                         
Array.129     1     1     1     1       HER2+  
Array.34      1     1     1     1         HR+  
Array.67      1     1     1     1         HR+  
Array.24      0     0     0     0  Triple Neg  
Array.22      1     1     1     1  Triple Neg  
...         ...   ...   ...   ...         ...  
Array.10      1     1     1     1       HER2+  
Array.123     1     1     1     1         HR+  
Array.100     1     1     1     1         HR+  
Array.134     1     1     1     1         HR+  
Array.130     1     1     1     1       HER2+  

[100 rows x 2835 columns]

# Support Vector Classification

In [92]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

In [129]:
# Separate the features and labels
#
X = trainset.iloc[:, :-1].values
y = trainset.iloc[:, -1].values

# Split the dataset into training and testing sets
#
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [130]:
# Scale the features
#
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [131]:
# Train the SVM model
#
classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [132]:
# Make predictions on the testing set
#
y_pred = classifier.predict(X_test)

# Evaluate the performance of the model
#
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)

Accuracy: 0.65
Confusion Matrix:
 [[4 1 0]
 [1 7 2]
 [1 2 2]]


# Naive Bayes Classification

In [133]:
from sklearn.naive_bayes import GaussianNB

In [135]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 70.00%


# Random Forest Classification

In [136]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [138]:
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 60.00%


In [140]:
from mlxtend.frequent_patterns import fpgrowth

In [142]:
LJEPs = fpgrowth(X_train, min_support=0.1, use_colnames=True)

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [ ]:

# transform the training and testing data into binary vectors based on the LJEPs
X_train_LJEP = X_train[:, LJEPs['itemsets'].values].astype(int)
X_test_LJEP = X_test[:, LJEPs['itemsets'].values].astype(int)

# create a Naive Bayes classifier
gnb = GaussianNB()

# train the classifier on the binary training data
gnb.fit(X_train_LJEP, y_train)

# predict the classes of the binary test data
y_pred = gnb.predict(X_test_LJEP)

# compute the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy: {:.2f}%".format(accuracy*100))